### ISSUE TITLE
How can I change the port from the default 8554?

### ISSUE THREAD

**Issue by gkouros** [CircusMonkey/ros_rtsp#1]
In my application, I want to stream multiple videos to different ports (eg. 8554, 9554 etc), but I have not found a way to do this with your code? Is it possible?

**Comment by gkouros** [comment]
Created a pull request that adds the option for custom port. You can either use a different port (other than 8554) for all the streams or you can launch multiple instances of the nodelet with different port configurations running on the same nodelet manager.

**Comment by Laxho** [comment]
Hi, hope you're doing awesome
have you find a way of having multiple clients connected to the same videosource?

**Comment by CircusMonkey** [comment]
Hi gkouros and Laxho,
I have merged #2 which should allow custom ports. I'll close this one off for now but I haven't tested it personally. Please let me know if I need to reopen it.
Cheers
