### ISSUE TITLE
VLC  error

### ISSUE THREAD

**Issue by yuqizhi** [CircusMonkey/ros_rtsp#10]
1. I run "roslaunch ros_rtsp rtsp_streams.lauch"successfully according to the readme method
![image](https://user-images.githubusercontent.com/53638072/126744983-f17def1c-91c7-4fea-aaf7-d2e0fb0b513f.png)

2. I use the local vlc player to connect
![image](https://user-images.githubusercontent.com/53638072/126745177-c78e4780-ccb5-4f4e-9f58-e84fa24eb9c7.png)
3. VLC error and con not play
![image](https://user-images.githubusercontent.com/53638072/126745311-63d83555-1edf-4770-88ac-bc8e43e53cbd.png)

**Comment by yuqizhi** [comment]
How can i solve this problem ？

**Comment by oponfil** [comment]
Try to install it using:
`sudo apt-get install gstreamer1.0-plugins-ugly`
It worked for me.

**Comment by yuqizhi** [comment]
@oponfil i install gstreamer1.0-plugins-ugly, although  the error has been redduced ,there are still 2 errors
![image](https://user-images.githubusercontent.com/53638072/128445695-76b2df24-e1d9-4f82-a6b5-c8a8af86f5b7.png)

**Comment by CircusMonkey** [comment]
Looks to be an issue with getting the image. What is config of the "front" camera that you are using?

**Comment by yuqizhi** [comment]
1.The parameters of my USB camera are as follows 
v4l2-ctl -d  /dev/video0 --all
Driver Info (not using libv4l2):
	Driver name   : uvcvideo
	Card type     : Rmoncam FHD 1080P: Rmoncam FHD 
	Bus info      : usb-0000:03:00.0-2
	Driver version: 4.15.18
	Capabilities  : 0x84200001
		Video Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps   : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
	Width/Height      : 1920/1080
	Pixel Format      : 'MJPG'
	Field             : None
	Bytes per Line    : 0
	Size Image        : 4147200
	Colorspace        : sRGB
	Transfer Function : Default
	YCbCr Encoding    : Default
	Quantization      : Default
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 1920, Height 1080
	Default     : Left 0, Top 0, Width 1920, Height 1080
	Pixel Aspect: 1/1
Selection: crop_default, Left 0, Top 0, Width 1920, Height 1080
Selection: crop_bounds, Left 0, Top 0, Width 1920, Height 1080
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 30.000 (30/1)
	Read buffers     : 0
                     brightness (int)    : min=-64 max=64 step=1 default=0 value=0
                       contrast (int)    : min=0 max=100 step=1 default=32 value=32
                     saturation (int)    : min=0 max=100 step=1 default=64 value=64
                            hue (int)    : min=-180 max=180 step=1 default=0 value=0
 white_balance_temperature_auto (bool)   : default=1 value=1
                          gamma (int)    : min=100 max=500 step=1 default=300 value=300
                           gain (int)    : min=1 max=128 step=1 default=64 value=64
           power_line_frequency (menu)   : min=0 max=2 default=1 value=1
      white_balance_temperature (int)    : min=2800 max=6500 step=10 default=4600 value=4600 flags=inactive
                      sharpness (int)    : min=0 max=100 step=1 default=50 value=50
         backlight_compensation (int)    : min=0 max=2 step=1 default=0 value=0
                  exposure_auto (menu)   : min=0 max=3 default=3 value=3
              exposure_absolute (int)    : min=50 max=10000 step=1 default=166 value=166 flags=inactive
         exposure_auto_priority (bool)   : default=0 value=1
2.  I modified the "stream_setup.yaml" file as follows:
# Set up your streams to rtsp here.
port: "8554"
streams: # Cannot rename - must leave this as is.

  stream-x:
    type: cam
    source: "v4l2src device=/dev/video0 ! videoconvert ! videoscale ! video/x-raw,framerate=15/1,width=1920,height=1080"
    mountpoint: /front
    bitrate: 500

  stream-yay:
    type: topic
    source: /usb_cam1/image_raw
    mountpoint: /back
    caps: video/x-raw,framerate=10/1,width=640,height=480
    bitrate: 500

**Comment by CircusMonkey** [comment]
Just throwing stuff out there,
Maybe try adjusting the caps in stream_setup.yaml:

```
stream-x:
type: cam
source: "v4l2src device=/dev/video0 ! videoconvert ! videoscale ! video/x-raw,width=640,height=480"
mountpoint: /front
bitrate: 500
```

This shrinks the video resolution and doesn't specify the framerate.
Also try with a framerate of 30/1 and 10/1. See if any of that makes a difference.

**Comment by CircusMonkey** [comment]
How did you go @yuqizhi ?

**Comment by CircusMonkey** [comment]
Closing this for now as original issue was resolved by installing the ugly plugins. Please open a new issue if you are still having trouble with your camera or let us know how you solved it!
