### ISSUE TITLE
GST_PIPELINE grammar.y:816:priv_gst_parse_yyparse: no element "x264enc"

### ISSUE THREAD

**Issue by armme41** [CircusMonkey/ros_rtsp#12]
I install this node on ubuntu 18.04 with melodic. When I use VLC to connect to the rtsp server, this node prints the following error:

> 0:07:41.178902242 11218 0x5581d8cc4f70 ERROR           GST_PIPELINE grammar.y:816:priv_gst_parse_yyparse: no element "x264enc"
> 0:07:41.178911425 11218 0x5581d8cc4f70 ERROR           GST_PIPELINE grammar.y:901:priv_gst_parse_yyparse: link has no sink [source=@0x7f94cc006d80]
> 0:07:41.178933565 11218 0x5581d8cc4f70 ERROR           GST_PIPELINE grammar.y:901:priv_gst_parse_yyparse: link has no source [sink=@0x7f94cc00a270]
> 0:07:41.270150981 11218 0x5581d8cc4f70 ERROR             rtspclient rtsp-client.c:1054:find_media: client 0x7f94f000a5a0: can't prepare media
> 0:07:41.270270203 11218 0x5581d8cc4f70 ERROR             rtspclient rtsp-client.c:2910:handle_describe_request: client 0x7f94f000a5a0: no media
> [ INFO] [1629166812.940669430]: New RTSP client
> 0:07:46.000311784 11218 0x7f94dc054c50 ERROR           GST_PIPELINE grammar.y:816:priv_gst_parse_yyparse: no element "x264enc"
> 0:07:46.000328290 11218 0x7f94dc054c50 ERROR           GST_PIPELINE grammar.y:901:priv_gst_parse_yyparse: link has no sink [source=@0x7f94e0009580]
> 0:07:46.000354271 11218 0x7f94dc054c50 ERROR           GST_PIPELINE grammar.y:901:priv_gst_parse_yyparse: link has no source [sink=@0x7f94e003c070]
> 0:07:46.061032460 11218 0x7f94dc054c50 ERROR             rtspclient rtsp-client.c:1054:find_media: client 0x7f94f000a490: can't prepare media
> 0:07:46.061180635 11218 0x7f94dc054c50 ERROR             rtspclient rtsp-client.c:2639:handle_setup_request: client 0x7f94f000a490: media '/back' not found

The issue can be solved by
`sudo apt install gstreamer1.0-libav gstreamer1.0-plugins-ugly`

Also, When I check the stream like this:

> gst-launch-1.0 -v rtspsrc location=rtsp://127.0.0.1:8554/back drop-on-latency=true use-pipeline-clock=true do-retransmission=false latency=0 protocols=GST_RTSP_LOWER_TRANS_UDP ! rtph264depay ! h264parse ! avdec_h264 ! autovideosink sync=true

I get:

> WARNING: erroneous pipeline: no element "h264parse"

Solve it by:
`sudo apt install gstreamer1.0-plugins-bad`

**Comment by CircusMonkey** [comment]
Thankyou @armme41. I've updated the readme to include the dependency. Better late than never!
