### ISSUE TITLE
Roslaunch shuts down after a while

### ISSUE THREAD

**Issue by akshata1100** [CircusMonkey/ros_rtsp#13]
Here's the error I getting- 

[ INFO] [1642740727.979080745]: Client connected: /back
[ERROR] [1642740930.640270278]: Exception thrown when deserializing message of length [921652] from [/usb_cam]: std::bad_alloc
[ERROR] [1642740930.705612519]: Exception thrown when deserializing message of length [921652] from [/usb_cam]: std::bad_alloc
[ERROR] [1642740930.738311305]: Exception thrown when deserializing message of length [921652] from [/usb_cam]: std::bad_alloc
[ERROR] [1642740930.805840695]: Exception thrown when deserializing message of length [921652] from [/usb_cam]: std::bad_alloc
[ERROR] [1642740930.878347705]: Exception thrown when deserializing message of length [921652] from [/usb_cam]: std::bad_alloc
[ERROR] [1642740930.909162431]: Exception thrown when deserializing message of length [921652] from [/usb_cam]: std::bad_alloc
[ERROR] [1642740930.938718362]: Exception thrown when deserializing message of length [921652] from [/usb_cam]: std::bad_alloc

(nodelet:5055): GLib-ERROR **: /build/glib2.0-4CLeJI/glib2.0-2.48.2/./glib/gmem.c:100: failed to allocate 921683 bytes
[standalone_nodelet-1] process has died [pid 5055, exit code -5, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=standalone_nodelet __log:=/home/ubuntu/.ros/log/67abd8b2-935e-11eb-b968-438b55e11b08/standalone_nodelet-1.log].
log file: /home/ubuntu/.ros/log/67abd8b2-935e-11eb-b968-438b55e11b08/standalone_nodelet-1*.log
[ INFO] [1642740934.303974307]: Bond broken, exiting
[Image2RTSPNodelet-2] process has finished cleanly
log file: /home/ubuntu/.ros/log/67abd8b2-935e-11eb-b968-438b55e11b08/Image2RTSPNodelet-2*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by CircusMonkey** [comment]
It may look like your computer is out of memory. Can you check if this is
the case?
"
(nodelet:5055): GLib-ERROR *:
/build/glib2.0-4CLeJI/glib2.0-2.48.2/./glib/gmem.c💯 failed to allocate
921683 bytes*
*"*

**Comment by akshata1100** [comment]
Possibly, let me try it in a different setup. Thank you for your response

**Comment by CircusMonkey** [comment]
How did this go @akshata1100, this might be the cause of your lag issue as well. What computer are you running the server on? Just wildly guessing it might be out of memory and also maxing out it's processor trying to encode the streams.

**Comment by akshata1100** [comment]
You were right, I was using dual boot Ubuntu system with low storage. I resolved this by using sufficient storage, doesn't appear to effect the lag though
