### ISSUE TITLE
Lag/Latency

### ISSUE THREAD

**Issue by akshata1100** [CircusMonkey/ros_rtsp#14]
When I stream rtsp to my VLC player there's almost 20-40s of lag in the stream.
I've tried almost everything. 
VLC doesn't play the rtsp if I change the config file (eh: bitrate/ width/height etc). 

What's the best solution to this?

**Comment by CircusMonkey** [comment]
Hi  @akshata1100, I don't recommend VLC for this at all but 20-40s of lag hints at some other problem. Try the other client commands below first to see if it's just a VLC issue:

How is the lag with the gstreamer or mpv commands?:
```bash
gst-launch-1.0 -v rtspsrc location=rtsp://127.0.0.1:8554/front drop-on-latency=true use-pipeline-clock=true do-retransmission=false latency=0 protocols=GST_RTSP_LOWER_TRANS_UDP ! rtph264depay ! h264parse ! avdec_h264 ! autovideosink sync=true
```
```bash
mpv --no-cache --untimed --no-demuxer-thread --vd-lavc-threads=1 rtsp://127.0.0.1:8554/front
```

 I've updated the example commands on the readme to include a different VLC command to try:
```bash
cvlc --no-audio --mux none --demux none --deinterlace 0 --no-autoscale --avcodec-hw=any --no-auto-preparse --sout-rtp-proto=udp --network-caching=300 --realrtsp-caching=0 --sout-udp-caching=0 --clock-jitter=0 --rtp-max-misorder=0 rtsp://127.0.0.1:8554/front :udp-timeout=0
```

**Comment by akshata1100** [comment]
Let me check this out. Thank you very much
