### ISSUE TITLE
node doesn't subscribe camera image

### ISSUE THREAD

**Issue by Bark33p3r** [CircusMonkey/ros_rtsp#16]
Hello, 
I guess I'm to stupid to use your node properly.

I'm running some ROS cameras from stemmer-imaging.
The output is a ROS-Topic which is called "/MonoLeft/image_raw"

My config file looks like this:
`
port: "8554"
streams:

  stream2:
    type: topic
    source: /MonoLeft/image_raw
    mountpoint: /back
    caps: video/x-raw,framerate=10/1,width=640,height=480
    bitrate: 800
`

When I check who subscribes this node I can't see the rtsp node
'rostopic info MonoLeft/image_raw'
`
Type: sensor_msgs/Image

Publishers: 
 * /cam2 (http://nano:32887/)

Subscribers: 
 * /rqt_gui_cpp_node_10987 (http://nano:45731/)
`
Like you see, there is an Video Output on the screen in a gui window which works.

'rostopic info /standalone_nodelet/bond' says:
`
Type: bond/Status

Publishers: 
 * /standalone_nodelet (http://nano:39081/)
 * /Image2RTSPNodelet (http://nano:39987/)

Subscribers: 
 * /standalone_nodelet (http://nano:39081/)
 * /Image2RTSPNodelet (http://nano:39987/)
`

ROS is running on a jetson nano (arm64 / aarch64)

Do you have any idea, what I'm doing wrong? Seems like it's working for some others. The image format is RAW.
May you can help me out?
Thanks a lot
Greetings 
Markus

**Comment by Bark33p3r** [comment]
Figured it out, I need to subscribe the rtsp stream that the node subscribes the topic.
Also I needed to do an image processing to change the format.
http://wiki.ros.org/image_proc

**Comment by CircusMonkey** [comment]
Thanks for following up with your solution!
