### ISSUE TITLE
Same source to different mountpoints

### ISSUE THREAD

**Issue by Laxho** [CircusMonkey/ros_rtsp#3]
Hello, first of all, I'm very thankful with you, this has helped me a lot!!!.

I wanted to ask you if it is possible to have different mountpoints that use the same webcam as video source. 
Thanks again Sam, you rock.

**Comment by CircusMonkey** [comment]
Hi Laxho,

Unfortunately once the camera resource is in use, you cannot access it again. There are solutions as there are a lot of powerful things you can do in gstreamer, however the learning curve is steep. This project trades off some gstreamer flexibility with trying to make it easier to use with ROS and I'm sorry but I will not get the time. If you would like to add it I would be very appreciative.

Some options you might want to explore are:
- Install a loopback driver to duplicate your v4l2 camera into a virtual camera.

- Look into gstreamer tees ([https://tewarid.github.io/2011/06/06/gstreamer-pipeline-with-tee.html](https://tewarid.github.io/2011/06/06/gstreamer-pipeline-with-tee.html))

**Comment by Laxho** [comment]
Sam,
Great, working on it.

**Comment by CircusMonkey** [comment]
How did you go with this Laxho?
