### ISSUE TITLE
can config to send to a rtsp server?

### ISSUE THREAD

**Issue by chenkaiC4** [CircusMonkey/ros_rtsp#4]
Nice Work!
how about config to send stream to rtsp server at the `stream_setup.yaml` file?

**Comment by CircusMonkey** [comment]
So do you already have a RSTP server setup and want to push an RTP stream from this script into it?

Is it an option to adjust src/video.cpp line 145 to add your server uri to the media factory?

Sorry I feel like setting up the rstp server is the hardest part of this little project. You probably don't need it if you already have an RSTP server.

**Comment by chenkaiC4** [comment]
thank you for your reply! I have changed my idea to send rstp stream to a another server. this is the one.
Sorry another question, this project not support compressed image, maybe this feature is useful.

share my Scene, i use a websocket to relay the rstp stream to web where i use flv.js to display video. :clinking_glasses:

**Comment by iceriver97** [comment]
how to support compressed image?

**Comment by CircusMonkey** [comment]
Tell us what you've tried, and what error messages you get. I'd suggest making a new issue because this one is unrelated to compressed images.
