### ISSUE TITLE
how to change the ip server address

### ISSUE THREAD

**Issue by Hanyouyu** [CircusMonkey/ros_rtsp#7]
Thank you  for your working.
the default ip address is 0.0.0.0
how I can change this to the address I want

**Comment by CircusMonkey** [comment]
Sorry Hanyouyu, this code doesn't control the server IP address. You need to configure the IP address using the OS on the system you are running this on.

The 0.0.0.0 just means that your computer will allow this RSTP server to be used over all of your network interfaces. I recommend you keep it as 0.0.0.0.

**Comment by mzahana** [comment]
@CircusMonkey I have an RTSP server that is running on a different machine with known IP and port. How can I use this package to stream a ROS image topic to that RTSP server?
If the source code is to be modified to enable this feature, which part of the code needs to be modified ?
Thanks in advance.
